version: "3.6"
services:
  app:
    build:
      context: ./
      dockerfile: docker/app/Dockerfile
      args:
        - REQUIREMENTS_FILE=app.pip
        - RBLOG_SECRET_KEY=$RBLOG_SECRET_KEY
        - DJANGO_SETTINGS_MODULE=rblog.settings.production
        - SUPERUSER_PASSWORD=$SUPERUSER_PASSWORD
        - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    image: elmcrest/rblog
    ports:
      - "8000:8000"
    environment:
      PYTHONUNBUFFERED: 1
      DJANGO_SETTINGS_MODULE: rblog.settings.production
      RBLOG_SECRET_KEY: $RBLOG_SECRET_KEY
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      SUPERUSER_PASSWORD: $SUPERUSER_PASSWORD
    links:
      - db_rblog
    volumes:
      - ./media:/app/media
    entrypoint: ["dumb-init", "docker/app/startup.sh"]

  db_rblog:
    image: "postgres:10.4-alpine"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD