# Generated by Django 2.0.6 on 2018-07-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='_created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='_updated')),
                ('published', models.DateTimeField(verbose_name='_published')),
                ('headline', models.CharField(max_length=200, verbose_name='_headline')),
                ('content', models.TextField(verbose_name='_content')),
                ('images', models.ManyToManyField(to='main.Image')),
            ],
        ),
    ]
