# Generated by Django 2.0.6 on 2018-07-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='items',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='article',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='menu',
        ),
        migrations.AddField(
            model_name='article',
            name='menu',
            field=models.CharField(blank=True, choices=[('main', 'main navigation')], default='main', max_length=20, verbose_name='menu'),
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
