# Generated by Django 2.0.6 on 2018-07-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180709_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='menu',
        ),
        migrations.AddField(
            model_name='article',
            name='in_menu',
            field=models.BooleanField(default=False, verbose_name='_in_menu'),
        ),
    ]
